baseurl = "https://robbertjan94.github.io/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Robbert-Jan 't Hoen"
theme = "hugo-lithium-theme"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "robbertjan94-github-io"
googleAnalytics = "UA-99839400-1"

[[menu.main]]
    name = "Post"
    url = "/post/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/page/about_me/"
    weight = 3

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[Author]
  name = "Robbert-Jan 't Hoen"
  email = "robbertjan-1994@hotmail.com"
  github = "robbertjan94"
  linkedin = "robbert-jan-t-hoen-b8930399"
  instagram = "robbertjan94"
  spotify = "1154803600"


