baseurl = "https://robbertjan94.github.io/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Robbert-Jan 't Hoen"
theme = "hugo-lithium-theme"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "robbertjan94-github-io"
googleAnalytics = "UA-99839400-1"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/page/about_me/"
    weight = 3

[params]
    description = ""
    favicon = "favicon.ico"
    
    [params.widgets]
    categories = true
    tags = true 
    categories_counter = true
    tags_counter = true 
    
    [params.logo]
    url = "logo_rj3.png"
    width = 50
    height = 50
    alt = "Logo" 
    
    [params.social]
    user = "Robbert-Jan 't Hoen"
    github = "robbertjan94"
    linkedin = "robbert-jan-t-hoen-b8930399"
    
    
[Author]
  name = "Robbert-Jan 't Hoen"
  email = "robbertjan-1994@hotmail.com"
  github = "robbertjan94"
  linkedin = "robbert-jan-t-hoen-b8930399"
  instagram = "robbertjan94"
  spotify = "1154803600"

[taxonomies]
   tag = "tags"
   category = "categories"


