---
date: 2017-05-22
description: "In this first blog post I describe my setup"
tags: [development, hugo, blogdown, github]
title: "Fist blog post"
---

Finally, after a few days of troubleshooting, I have succeeded in launching my first website with <a href="https://gohugo.io/">Hugo</a>!   

My current setup is <a href="https://pages.github.com/">GitHub Pages</a> + Hugo + <a href="https://github.com/rstudio/blogdown">Blogdown</a> as described in this excellent <a href="https://proquestionasker.github.io/blog/Making_Site/"> tutorial</a> by <a href="https://github.com/ProQuestionAsker">Amber Thomas</a>. This allows me to create rich web content by utilizing <a href="http://rmarkdown.rstudio.com/">Rmarkdown</a> files with the blogdown package in Rstudio. I chose to use Hugo because it produces static websites. The idea of a static website is that websites are viewed far more often than they are edited, hence the building is only done when the content is created. Another important feature of Hugo are the hundreds of themes that are available through the <a href="https://themes.gohugo.io/">theme gallery</a>. Most themes are not that great, however, there are some very beautiful themes to choose from. I decided to use the <a href="https://themes.gohugo.io/beautifulhugo/">beautiful hugo</a> theme. 